quadruped:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# controllers
  sholder1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: sholder1_joint
    pid: {p: 200.0, i: 30.0, d: 1.0}
  sholder2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: sholder2_joint
    pid: {p: 200.0, i: 30.0, d: 1.0}
  sholder3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: sholder3_joint
    pid: {p: 200.0, i: 30.0, d: 1.0}
  sholder4_joint_controller:
    type: effort_controllers/JointPositionController
    joint: sholder4_joint
    pid: {p: 200.0, i: 30.0, d: 1.0}
